### PR TITLE
Procedurally determine HEADER_SEARCH_PATHS for iOS builds

### LINKED ISSUE #327: Ensure SDK works if asset is nested in Unity project
**Context:** Developers often move external plugins inside their projects for organization purposes or to decrease compile times.

**Problem:** Apparently, moving the Mapbox asset will cause iOS builds to fail due to some "hardcoded" paths. Reference: https://github.com/mapbox/mapbox-unity-sdk/issues/301#issuecomment-339650769

**Solution:**  Let's ensure iOS dependencies do not have hardcoded paths or that the paths can be found procedurally as part of a build step. Perhaps inside https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs?

**Next Steps**
- [ ] Investigate and reproduce the issue
- [ ] Procedurally identify location of required libraries in build scripts

### PR DESCRIPTION
**Pull request by noodle**
Resolves #327.  The build step now searches all of `Application.dataPath` for the iOS include directory.

### CODE REVIEW

**Comment by noodle** [comment]
Ready for review at your convenience, @david-rhodes.

File: sdkproject/Assets/Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs [hunk 1]
```diff
@@ -22,7 +24,15 @@ public static void AppendBuildProperty(BuildTarget buildTarget, string pathToBui
 				proj.ReadFromString(file);
 				string target = proj.TargetGuidByName("Unity-iPhone");
 
-				proj.AddBuildProperty(target, "HEADER_SEARCH_PATHS", "$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include");
+				var defaultIncludePath = "Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include";
+				var includePaths = Directory.GetDirectories(Application.dataPath, "include", SearchOption.AllDirectories);
+				var includePath = includePaths
+					.Select(path => Regex.Replace(path, Application.dataPath + "/", ""))
+					.Where(path => path.EndsWith(defaultIncludePath))
```
Comment (david-rhodes) [inline sdkproject/Assets/Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs]: Can you make this case insensitive and culture invariant, please?

Comment (noodle) [reply sdkproject/Assets/Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs]: Of course, done.
