### PR TITLE
Replace hero buildings

### LINKED ISSUE #658: Geocode search windows can incorrectly convert doubles
When using the geocode search window to find locations, in some locales the gps coordinates will get formatted with a comma instead of a dot, e.g.:

"42,23551, 33,123555" instead of "42.23551, 33.123555 ".

AbstractMap will then not be able to parse the coordinates.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.0b12
* Mapbox SDK version: 1.4

```
[Exception] ArgumentException: Wrong number of arguments
Conversions.StringToLatLon()    Assets/Addons/Mapbox/Unity/Utilities/Conversions.cs:48
AbstractMap.InitializeMap()    Assets/Addons/Mapbox/Unity/Map/AbstractMap.cs:420
AbstractMap.SetUpMap()    Assets/Addons/Mapbox/Unity/Map/AbstractMap.cs:395
AbstractMap.Start()    Assets/Addons/Mapbox/Unity/Map/AbstractMap.cs:291
```
```
[Exception] NullReferenceException: Object reference not set to an instance of an object
RangeTileProvider.Update()    Assets/Addons/Mapbox/Unity/Map/RangeTileProvider.cs:47
```

### PR DESCRIPTION
**Pull request by apavani**
Closes https://github.com/mapbox/unity/issues/658 
**Description of changes**
Added a way to replace buildings with a spawned prefab at the specified lat, lon.
We have an asset from Google Poly in the examples folder, which if we include we should mention an attribution somewhere. If not, we need to create our own rocket launch pad station asset for demo purposes.

@BergWerkGIS This is how we are handling replacing of multiple parts of the same building.
https://github.com/mapbox/mapbox-unity-sdk/blob/replace-hero-buildings/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/ReplaceFeatureModifier.cs#L67-L68

 

**QA checklists**

- [x] Add relevant code comments. Every API class and method should have `<summary>` description as well as description of parameters.
- [ ] **Add tests for new/changed/updated classes and methods!!!**
- [x] Check out conventions in [CONTRIBUTING.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CONTRIBUTING.md).
- [x] Check out conventions in [CODING-STYLE.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CODING-STYLE.md)
- [x] Update the [changelog](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/documentation/docs/05-changelog.md)
- [ ] Update documentation.

**Reviewers**

Tag your reviewer(s). Choose wisely.

### CODE REVIEW

File: sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/GameObjectModifiers/PrefabModifier.cs [hunk 1]
```diff
@@ -31,8 +31,14 @@ public override void SetProperties(ModifierProperties properties)
 
 		public override void Run(VectorEntity ve, UnityTile tile)
 		{
-			int selpos = ve.Feature.Points[0].Count / 2;
-			var met = ve.Feature.Points[0][selpos];
+			//int selpos = ve.Feature.Points[0].Count / 2;
+			var met = new Vector3();
```
Comment (BergWerkGIS) [inline sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/GameObjectModifiers/PrefabModifier.cs]: What's `met`?
Please use self explaining variable names.

File: sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/ReplaceFeatureModifier.cs [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+		public bool ShouldReplaceFeature( VectorFeatureUnity feature )
+		{
+			foreach( var point in _prefabLocations )
+			{
+				var coord = Conversions.StringToLatLon(point);
+				if (feature.ContainsLatLon(coord))
+				{
+
+
+					if(feature.Data.Id != null && !string.IsNullOrEmpty(feature.Data.Id.ToString()) && String.IsNullOrEmpty(_featureId))
```
Comment (BergWerkGIS) [inline sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/ReplaceFeatureModifier.cs]: `Id` is of type [`ulong`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ulong) which has [a default value of `0`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/default-values-table).

This means that the first two conditions in this `if` clause will always evalute to `true`.

Please fix.

File: sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/ReplaceFeatureModifier.cs [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+			if(ShouldSpawnFeature(ve.Feature))
+			{
+				SpawnPrefab(ve, tile);
+			}
+		}
+
+		private void SpawnPrefab(VectorEntity ve, UnityTile tile)
+		{
+			//int selpos = ve.Feature.Points[0].Count / 2;
+			var met = new Vector3();
```
Comment (BergWerkGIS) [inline sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/ReplaceFeatureModifier.cs]: Same as in `PrefabModifier.cs`: what's `met`?

File: sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/UvModifier.cs [hunk 4]
```diff
@@ -38,8 +38,12 @@ public override void SetProperties(ModifierProperties properties)
 
 		public override void Run(VectorFeatureUnity feature, MeshData md, UnityTile tile = null)
 		{
+			if (md.Vertices.Count == 0 || feature == null || feature.Points.Count < 1)
```
Comment (BergWerkGIS) [inline sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/UvModifier.cs]: Please use braces even for single line code blocks.
https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CODING-STYLE.md

File: sdkproject/Assets/Mapbox/Unity/Utilities/PolygonUtils.cs [hunk 5]
```diff
@@ -0,0 +1,39 @@
+﻿using UnityEngine;
+using System.Collections.Generic;
+using Mapbox.VectorTile.Geometry;
+using Mapbox.VectorTile.Geometry.InteralClipperLib;
```
Comment (BergWerkGIS) [inline sdkproject/Assets/Mapbox/Unity/Utilities/PolygonUtils.cs]: Using `clipper` works for now, but be aware that this will break once our VT APIs support server side clipping (no ETA yet) and `vector-tile-cs` will drop that dependency.

Comment (apavani) [reply sdkproject/Assets/Mapbox/Unity/Utilities/PolygonUtils.cs]: @BergWerkGIS What is `server side clipping` meant to do?

**Comment by apavani** [comment]
Fixed the issues pointed out by @BergWerkGIS. @brnkhy Can you please add your changes by tomorrow so that we can get this merged. 🙏

File: sdkproject/Assets/Mapbox/Unity/Utilities/PolygonUtils.cs (hunk 5 above)
Comment (BergWerkGIS) [reply sdkproject/Assets/Mapbox/Unity/Utilities/PolygonUtils.cs]: yes, server side clipping.
